debug: true
discord:
  token: YOUR_TOKEN_HERE
  status: Bocchi-Go is running! | b.help
chat:
  chattoken: YOUR_TOKEN_HERE
guild:
  prefix: b.
  lang: japanese
  model: gpt-3.5-turbo
  timeout: 120
user_blacklist:
- "0000000000000000000"
