debug: true
discord:
  token: YOUR_TOKEN_HERE
  status: ChatGPT is running! | b.help
chat:
  chattoken: YOUR_TOKEN_HERE
guild:
  prefix: b.
  lang: japanese
  maxtoken: 4095
user_blacklist:
- "0000000000000000000"
