debug: true
help: https://github.com/tpc3/Bocchi-Go/wiki
discord:
  token: YOUR_TOKEN_HERE
  status: ChatGPT is running! | g.help
chat:
  chattoken: YOUR_TOKEN_HERE
guild:
  prefix: g.
  lang: japanese
  enabledeepl: false
  maxtoken: 4095
user_blacklist:
- "0000000000000000000"
